import { and, asc, eq, inArray } from "drizzle-orm"
import { db } from "@/db/client"
import { cards, issuers, sourceDocuments } from "@/db/schema/catalog"
import {
  crossCheckGroups,
  reviewTasks,
  sourceClaims,
} from "@/db/schema/extraction"

// Server query for /review/[taskId] (P6). Loads the task, its
// cross_check_group (always set when the task came from P4), and every
// supporting / contradicting claim with the source it came from. The
// detail page renders these as a side-by-side comparison so the reviewer
// can see the LLM's extracted_text_snippet next to the structured payload.
//
// Single round trip strategy: 1 query for the task+group+card+issuer,
// then 1 query for every claim in supporting∪contradicting (the IN array
// is small — at most ~10 claims per group in our data). Sources for the
// claims join in the second query.

export type ReviewTaskDetail = {
  task: {
    id: string
    taskType: string
    priority: string
    status: string
    title: string
    description: string | null
    resolutionNote: string | null
    resolvedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }
  card: {
    id: string
    slug: string
    cardNameEn: string
    issuerNameEn: string
  }
  group: {
    id: string
    claimType: string
    keyDimension: string
    status: string
    canonicalPayload: unknown
    aggregateConfidence: string
    supportingClaimIds: string[]
    contradictingClaimIds: string[]
  } | null
  claims: ReviewClaim[]
}

export type ReviewClaim = {
  id: string
  status: string
  isSupporting: boolean // membership in group.supportingClaimIds
  extractedTextSnippet: string
  structuredPayload: unknown
  confidenceScore: string
  reviewerNote: string | null
  extractedBy: string
  createdAt: Date
  source: {
    id: string
    slug: string
    title: string
    sourceType: string
    sourcePriority: number
    url: string | null
  }
}

export async function getReviewTaskDetail(
  taskId: string,
): Promise<ReviewTaskDetail | null> {
  const headRows = await db
    .select({
      task: reviewTasks,
      group: crossCheckGroups,
      card: cards,
      issuer: issuers,
    })
    .from(reviewTasks)
    .innerJoin(cards, eq(reviewTasks.cardId, cards.id))
    .innerJoin(issuers, eq(cards.issuerId, issuers.id))
    .leftJoin(
      crossCheckGroups,
      eq(reviewTasks.subjectGroupId, crossCheckGroups.id),
    )
    .where(eq(reviewTasks.id, taskId))
    .limit(1)

  const head = headRows[0]
  if (!head) return null

  // Pull every claim cited by the group (supporting + contradicting),
  // joined to its source. For tasks without a group (manual claim_review
  // flows — not generated by P4 today), fall back to subjectClaimId only.
  let claimIds: string[] = []
  let supportingSet = new Set<string>()
  if (head.group) {
    claimIds = [
      ...head.group.supportingClaimIds,
      ...head.group.contradictingClaimIds,
    ]
    supportingSet = new Set(head.group.supportingClaimIds)
  } else if (head.task.subjectClaimId) {
    claimIds = [head.task.subjectClaimId]
    supportingSet = new Set([head.task.subjectClaimId])
  }

  const claims: ReviewClaim[] =
    claimIds.length === 0
      ? []
      : (
          await db
            .select({
              claim: sourceClaims,
              source: sourceDocuments,
            })
            .from(sourceClaims)
            .innerJoin(sourceDocuments, eq(sourceClaims.sourceId, sourceDocuments.id))
            .where(
              and(
                inArray(sourceClaims.id, claimIds),
                // Defensive: only include claims actually in this card. Same
                // card_id is already enforced by the group, but cheap to add.
                eq(sourceClaims.cardId, head.card.id),
              ),
            )
            // Priority-asc puts P1 (official PDF) first, then P2 (official
            // page), etc. — reviewer reads from most authoritative downward.
            // Tiebreak on createdAt so re-runs see the same order.
            .orderBy(asc(sourceDocuments.sourcePriority), asc(sourceClaims.createdAt))
        ).map((r) => ({
          id: r.claim.id,
          status: r.claim.status,
          isSupporting: supportingSet.has(r.claim.id),
          extractedTextSnippet: r.claim.extractedTextSnippet,
          structuredPayload: r.claim.structuredPayload,
          confidenceScore: r.claim.confidenceScore,
          reviewerNote: r.claim.reviewerNote,
          extractedBy: r.claim.extractedBy,
          createdAt: r.claim.createdAt,
          source: {
            id: r.source.id,
            slug: r.source.slug,
            title: r.source.title,
            sourceType: r.source.sourceType,
            sourcePriority: r.source.sourcePriority,
            url: r.source.url,
          },
        }))

  return {
    task: {
      id: head.task.id,
      taskType: head.task.taskType,
      priority: head.task.priority,
      status: head.task.status,
      title: head.task.title,
      description: head.task.description,
      resolutionNote: head.task.resolutionNote,
      resolvedAt: head.task.resolvedAt,
      createdAt: head.task.createdAt,
      updatedAt: head.task.updatedAt,
    },
    card: {
      id: head.card.id,
      slug: head.card.slug,
      cardNameEn: head.card.cardNameEn,
      issuerNameEn: head.issuer.nameEn,
    },
    group: head.group
      ? {
          id: head.group.id,
          claimType: head.group.claimType,
          keyDimension: head.group.keyDimension,
          status: head.group.status,
          canonicalPayload: head.group.canonicalPayload,
          aggregateConfidence: head.group.aggregateConfidence,
          supportingClaimIds: head.group.supportingClaimIds,
          contradictingClaimIds: head.group.contradictingClaimIds,
        }
      : null,
    claims,
  }
}
